name: Java CI with Gradle and Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Build with Gradle
        run: |
          echo ${{secrets.secret}} | base64 --decode > ./src/main/resources/application.yml
          
      - name: Set up OpenJDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.12.1'

      - name: Clear Gradle Cache
        run: ./gradlew clean

      - name: Build with Gradle Wrapper
        run: ./gradlew build --info

      - name: Run tests
        run: ./gradlew test --info

      - name: Build Docker image
        run: |
          docker build -t sipkh85wzdrg7ivsyep7/ewrthgsdkfhfsghjhgklsj:latest .

      - name: Login docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish to docker hub
        run: docker push docker.io/sipkh85wzdrg7ivsyep7/ewrthgsdkfhfsghjhgklsj

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      security-events: write  
    steps:
      - uses: actions/checkout@v4

      - name: Set up OpenJDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
        with:
          dependency-graph: generate-and-submit
          dependency-graph-report-dir: ./reports/dependency-graph
